<template>
<sensorvalue>
<port>FR</port>
<entity>
<eorder>7</eorder>
<ename>Last Remote </ename>
<eicon>f10a</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>NR</port>
<entity>
<eorder>11</eorder>
<ename>Noise Ratio</ename>
<eicon>f519</eicon>
<euom>dBm</euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>RS</port>
<entity>
<eorder>10</eorder>
<ename>RSSI</ename>
<eicon>f09e</eicon>
<euom>dBm</euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>CS</port>
</sensorvalue>
<sensorvalue>
<port>DT</port>
</sensorvalue>
<sensorvalue>
<port>#G</port>
<endpoint>
<epid>0</epid>
<actionname>Open Gate</actionname>
<endpointport>
<endpointporttype>#G</endpointporttype>
<endpointportvalue>0</endpointportvalue>
</endpointport>
</endpoint>
<endpoint>
<epid>1</epid>
<actionname>Close Gate</actionname>
<endpointport>
<endpointporttype>#G</endpointporttype>
<endpointportvalue>1</endpointportvalue>
</endpointport>
</endpoint>
<endpoint>
<epid>2</epid>
<actionname>Open Auto Close Gate</actionname>
<endpointport>
<endpointporttype>#G</endpointporttype>
<endpointportvalue>2</endpointportvalue>
</endpointport>
</endpoint>
<endpoint>
<epid>3</epid>
<actionname>Toggle Gate</actionname>
<endpointport>
<endpointporttype>#G</endpointporttype>
<endpointportvalue>3</endpointportvalue>
</endpointport>
</endpoint>
</sensorvalue>
<sensorvalue>
<port>SM</port>
</sensorvalue>
<sensorvalue>
<port>SA</port>
<entity>
<eorder>4</eorder>
<ename>Solar Amps</ename>
<eicon>f0e7</eicon>
<euom>A</euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>SV</port>
<entity>
<eorder>3</eorder>
<ename>Solar Voltage</ename>
<eicon>f5ba</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>IV</port>
<entity>
<eorder>2</eorder>
<ename>Battery Voltage</ename>
<eicon>f5df</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>GS</port>
<entity>
<eorder>1</eorder>
<ename>Gate Status</ename>
<eicon>f52b</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Opening</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>2.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Open</hname>
<htest>3</htest>
<hhighlight>3</hhighlight>
<hval1>3.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Closing</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Closed</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>MR</port>
<entity>
<eorder>6</eorder>
<ename>Message Reason</ename>
<eicon>f071</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>HB</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Btn</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Fob</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>2.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>LoRa</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>3.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>BT</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>4.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Shd</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>5.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Stp</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>6.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>MI</port>
<entity>
<eorder>5</eorder>
<ename>Message ID</ename>
<eicon>f27a</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
</template>
