<template>
<header>
<dtid>7</dtid>
<dtcat>7</dtcat>
<dthw>1.6</dthw>
<minfw>1.7</minfw>
</header>
<sensorvalue>
<port>RI</port>
<entity>
<eorder>1</eorder>
<ename>RouterID</ename>
<eicon>f577</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat>Ignore</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>NR</port>
<entity>
<eorder>11</eorder>
<ename>SNR</ename>
<eicon>e012</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>RS</port>
<entity>
<eorder>10</eorder>
<ename>RSSI</ename>
<eicon>f09e</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>100.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>100.00</hval1>
<hval2>110.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Poor</hname>
<htest>1</htest>
<hhighlight>3</hhighlight>
<hval1>110.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>CS</port>
</sensorvalue>
<sensorvalue>
<port>PN</port>
<entity>
<eorder>7</eorder>
<ename>Visible Nodes</ename>
<eicon>f0ca</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat>Ignore</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>RN</port>
<entity>
<eorder>6</eorder>
<ename>Number Routed</ename>
<eicon>f6ff</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat>Ignore</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>RE</port>
<entity>
<eorder>5</eorder>
<ename>Routing</ename>
<eicon>f205</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat>Ignore</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>On</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Off</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>DT</port>
</sensorvalue>
<sensorvalue>
<port>SM</port>
</sensorvalue>
<sensorvalue>
<port>P3</port>
<entity>
<eorder>2</eorder>
<ename>Battery Voltage</ename>
<eicon>f242</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1024</tname>
<tvalfrom>1024.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>*5</tname>
<tvalfrom>5.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>IV</port>
<entity>
<eorder>3</eorder>
<ename>Regulated Out</ename>
<eicon>f201</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>*3.3</tname>
<tvalfrom>3.30</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1024</tname>
<tvalfrom>1024.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/0.2618</tname>
<tvalfrom>0.26</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>4.99</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Low</hname>
<htest>0</htest>
<hhighlight>2</hhighlight>
<hval1>5.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>MR</port>
</sensorvalue>
<sensorvalue>
<port>MI</port>
</sensorvalue>
</template>
