<template>
<sensorvalue>
<port>NR</port>
<entity>
<eorder>11</eorder>
<ename>Signal to Noise</ename>
<eicon>e012</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>Raw</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>150.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>95.00</hval1>
<hval2>105.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Poor</hname>
<htest>0</htest>
<hhighlight>3</hhighlight>
<hval1>95.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>RS</port>
<entity>
<eorder>10</eorder>
<ename>RSSI</ename>
<eicon>f09e</eicon>
<euom>dBm</euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>100.00</hval1>
<hval2>110.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Good</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>100.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Bad</hname>
<htest>1</htest>
<hhighlight>3</hhighlight>
<hval1>110.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Poor</hname>
<htest>1</htest>
<hhighlight>3</hhighlight>
<hval1>110.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>CS</port>
</sensorvalue>
<sensorvalue>
<port>SM</port>
</sensorvalue>
<sensorvalue>
<port>HS</port>
<entity>
<eorder>12</eorder>
<ename>Uptime</ename>
<eicon>f011</eicon>
<euom>days</euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>HN</port>
<entity>
<eorder>12</eorder>
<ename>Max Power Yesterday</ename>
<eicon>e098</eicon>
<euom>W</euom>
<showstatus>0</showstatus>
<mqttcat>power</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>HM</port>
<entity>
<eorder>7</eorder>
<ename>Yield Yesterday</ename>
<eicon>f272</eicon>
<euom>Wh</euom>
<showstatus>0</showstatus>
<mqttcat>energy</mqttcat>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>X10</tname>
<tvalfrom>10.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>HL</port>
<entity>
<eorder>12</eorder>
<ename>Max Power Today</ename>
<eicon>e098</eicon>
<euom>W</euom>
<showstatus>0</showstatus>
<mqttcat>power</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>HK</port>
<entity>
<eorder>6</eorder>
<ename>Yield Today</ename>
<eicon>f783</eicon>
<euom>Wh</euom>
<showstatus>0</showstatus>
<mqttcat>energy</mqttcat>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>X10</tname>
<tvalfrom>10.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>HJ</port>
<entity>
<eorder>8</eorder>
<ename>Solar Total</ename>
<eicon>f185</eicon>
<euom>kWh</euom>
<showstatus>0</showstatus>
<mqttcat>energy</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/100</tname>
<tvalfrom>100.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>IL</port>
<entity>
<eorder>3</eorder>
<ename>Load Current</ename>
<eicon>f0e7</eicon>
<euom>A</euom>
<showstatus>0</showstatus>
<mqttcat>current</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>High</hname>
<htest>1</htest>
<hhighlight>2</hhighlight>
<hval1>15.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>LD</port>
<entity>
<eorder>2</eorder>
<ename>Load Status</ename>
<eicon>f204</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>On</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Off</hname>
<htest>3</htest>
<hhighlight>3</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>ER</port>
<entity>
<eorder>12</eorder>
<ename>Error Code</ename>
<eicon>f071</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat></mqttcat>
<highlight>
<hname>No Errors</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Voltage High</hname>
<htest>3</htest>
<hhighlight>3</hhighlight>
<hval1>2.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Charge Temp</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>17.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Charge Over Cur</hname>
<htest>3</htest>
<hhighlight>3</hhighlight>
<hval1>18.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Bulk time limit</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>20.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>High Input V</hname>
<htest>3</htest>
<hhighlight>3</hhighlight>
<hval1>33.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>OR</port>
</sensorvalue>
<sensorvalue>
<port>MT</port>
<entity>
<eorder>12</eorder>
<ename>MQTT Mode</ename>
<eicon>f074</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Off</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Limited</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Active</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>2.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>PV</port>
<entity>
<eorder>5</eorder>
<ename>Solar Power</ename>
<eicon>f6c4</eicon>
<euom>W</euom>
<showstatus>0</showstatus>
<mqttcat>power</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>D10</tname>
<tvalfrom>10.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>VV</port>
<entity>
<eorder>4</eorder>
<ename>Solar Voltage</ename>
<eicon>f5ba</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>D1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>5</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>Zero it</tname>
<tvalfrom>0.01</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>40.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>1</hhighlight>
<hval1>13.70</hval1>
<hval2>40.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Low</hname>
<htest>0</htest>
<hhighlight>2</hhighlight>
<hval1>13.70</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>I_</port>
<entity>
<eorder>12</eorder>
<ename>Solar Current</ename>
<eicon>f0e7</eicon>
<euom>A</euom>
<showstatus>0</showstatus>
<mqttcat>current</mqttcat>
<translation>
<ttype>11</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>ConvertNeg</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>10.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>10.00</hval1>
<hval2>15.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>High</hname>
<htest>1</htest>
<hhighlight>3</hhighlight>
<hval1>15.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>V_</port>
<entity>
<eorder>1</eorder>
<ename>Battery Voltage</ename>
<eicon>f5df</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>d1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>13.30</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Used</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>12.20</hval1>
<hval2>13.30</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Bad</hname>
<htest>0</htest>
<hhighlight>3</hhighlight>
<hval1>12.20</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>FW</port>
</sensorvalue>
<sensorvalue>
<port>PD</port>
</sensorvalue>
<sensorvalue>
<port>IV</port>
<entity>
<eorder>12</eorder>
<ename>NodeVoltage</ename>
<eicon>f011</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>x3.3</tname>
<tvalfrom>3.30</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1024</tname>
<tvalfrom>1024.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/0.25</tname>
<tvalfrom>0.25</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>G3.4</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>3.40</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Low</hname>
<htest>0</htest>
<hhighlight>2</hhighlight>
<hval1>3.40</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>IH</port>
<entity>
<eorder>5</eorder>
<ename>Humidity</ename>
<eicon>f043</eicon>
<euom>%</euom>
<showstatus>0</showstatus>
<mqttcat>humidity</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>60.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>IT</port>
<entity>
<eorder>12</eorder>
<ename>Temp</ename>
<eicon>f2c8</eicon>
<euom>°C</euom>
<showstatus>0</showstatus>
<mqttcat>temperature</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>MR</port>
<entity>
<eorder>12</eorder>
<ename>Message Reason</ename>
<eicon>f0f3</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat>Ignore</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>WakeUp</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>MI</port>
<entity>
<eorder>12</eorder>
<ename>Message ID#</ename>
<eicon>f27a</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>DT</port>
<entity>
<eorder>12</eorder>
<ename>Device Type</ename>
<eicon>f059</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat>Ignore</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>raw</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Custom</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Water Tank Sensor</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Victron SmartSolar</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>2.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Remote PIR</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>3.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Remote Gate</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>4.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Electric Fence</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>5.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>SOS Device</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>6.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Repeater</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>7.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Water Flow Switch</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>8.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
</template>
