<template>
<header>
<dtid>0</dtid>
<dtcat>0</dtcat>
<dthw>1.0</dthw>
<minfw>0</minfw>
</header>
<sensorvalue>
<port>NR</port>
<entity>
<eorder>11</eorder>
<ename>Noise Ratio</ename>
<eicon>e012</eicon>
<euom>dBm</euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>RS</port>
<entity>
<eorder>10</eorder>
<ename>RSSI</ename>
<eicon>f09e</eicon>
<euom>dBm</euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>CS</port>
</sensorvalue>
<sensorvalue>
<port>DT</port>
</sensorvalue>
<sensorvalue>
<port>SM</port>
</sensorvalue>
<sensorvalue>
<port>IV</port>
<entity>
<eorder>1</eorder>
<ename>Internal Voltage</ename>
<eicon>f241</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>battery</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>100.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>MI</port>
<entity>
<eorder>5</eorder>
<ename>Message #</ename>
<eicon>f27a</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
</template>
