<template>
<header>
<dtid>7</dtid>
<dtcat>7</dtcat>
<dthw>1.2</dthw>
<minfw>0</minfw>
</header>
<sensorvalue>
<port>MI</port>
</sensorvalue>
<sensorvalue>
<port>MR</port>
</sensorvalue>
<sensorvalue>
<port>IT</port>
<entity>
<eorder>6</eorder>
<ename>Temperature </ename>
<eicon>f2c8</eicon>
<euom>C</euom>
<showstatus>0</showstatus>
<mqttcat>temperature</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>IH</port>
<entity>
<eorder>5</eorder>
<ename>Humidity</ename>
<eicon>f043</eicon>
<euom>%</euom>
<showstatus>0</showstatus>
<mqttcat>humidity</mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>IV</port>
<entity>
<eorder>4</eorder>
<ename>Regulated Out</ename>
<eicon>f201</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>*3.3</tname>
<tvalfrom>3.30</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1024</tname>
<tvalfrom>1024.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/0.2618</tname>
<tvalfrom>0.26</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>4.99</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Low</hname>
<htest>0</htest>
<hhighlight>2</hhighlight>
<hval1>5.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>SM</port>
</sensorvalue>
<sensorvalue>
<port>DT</port>
</sensorvalue>
<sensorvalue>
<port>CS</port>
</sensorvalue>
<sensorvalue>
<port>RS</port>
<entity>
<eorder>1</eorder>
<ename>RSSI</ename>
<eicon>f09e</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>100.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>100.00</hval1>
<hval2>110.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Poor</hname>
<htest>1</htest>
<hhighlight>3</hhighlight>
<hval1>110.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>NR</port>
<entity>
<eorder>2</eorder>
<ename>SNR</ename>
<eicon>e012</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
<sensorvalue>
<port>P3</port>
<entity>
<eorder>3</eorder>
<ename>Battery Voltage</ename>
<eicon>f242</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1024</tname>
<tvalfrom>1024.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>4</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>*5</tname>
<tvalfrom>5.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
</template>
