<template>
<header>
<dtid>1</dtid>
<dtcat>1</dtcat>
<dthw>1.6</dthw>
<minfw>0</minfw>
</header>
<sensorvalue>
<port>NR</port>
<entity>
<eorder>11</eorder>
<ename>Noise Ratio</ename>
<eicon>e012</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>105.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>95.00</hval1>
<hval2>105.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Poor</hname>
<htest>0</htest>
<hhighlight>3</hhighlight>
<hval1>95.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>RS</port>
<entity>
<eorder>10</eorder>
<ename>RSSI</ename>
<eicon>f09e</eicon>
<euom>db</euom>
<showstatus>0</showstatus>
<mqttcat>signal_strength</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>6</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>maxx200</tname>
<tvalfrom>200.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>90.00</hval1>
<hval2>110.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Unreliable</hname>
<htest>1</htest>
<hhighlight>3</hhighlight>
<hval1>110.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Good</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>90.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>CS</port>
</sensorvalue>
<sensorvalue>
<port>DT</port>
<entity>
<eorder>12</eorder>
<ename>Device Type</ename>
<eicon>f773</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat>Ignore</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Tank Level v1.5</hname>
<htest>3</htest>
<hhighlight>0</hhighlight>
<hval1>10.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>SM</port>
</sensorvalue>
<sensorvalue>
<port>P3</port>
<entity>
<eorder>3</eorder>
<ename>Solar Charge Voltage</ename>
<eicon>f185</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Low Power</hname>
<htest>0</htest>
<hhighlight>0</hhighlight>
<hval1>5.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>5.00</hval1>
<hval2>6.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>6.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>P2</port>
<entity>
<eorder>1</eorder>
<ename>Tank Level</ename>
<eicon>f773</eicon>
<euom>mm</euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>5</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>zerolevel</tname>
<tvalfrom>490.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>7</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>Min0</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>Factor</tname>
<tvalfrom>1.26</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>1000.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>1000.00</hval1>
<hval2>600.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Low</hname>
<htest>0</htest>
<hhighlight>1</hhighlight>
<hval1>600.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>P1</port>
<entity>
<eorder>4</eorder>
<ename>P1 Binary Switch</ename>
<eicon>f52b</eicon>
<euom></euom>
<showstatus>1</showstatus>
<mqttcat>Ignore</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>0</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>NewTrans</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Closed</hname>
<htest>3</htest>
<hhighlight>1</hhighlight>
<hval1>0.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Open</hname>
<htest>3</htest>
<hhighlight>2</hhighlight>
<hval1>1.00</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>IV</port>
<entity>
<eorder>2</eorder>
<ename>Super Cap Voltage</ename>
<eicon>f242</eicon>
<euom>V</euom>
<showstatus>0</showstatus>
<mqttcat>voltage</mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>9</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>/1000</tname>
<tvalfrom>1000.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
<highlight>
<hname>Low</hname>
<htest>0</htest>
<hhighlight>3</hhighlight>
<hval1>4.50</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>OK</hname>
<htest>2</htest>
<hhighlight>2</hhighlight>
<hval1>3.50</hval1>
<hval2>3.30</hval2>
<hsound>0</hsound>
</highlight>
<highlight>
<hname>Good</hname>
<htest>1</htest>
<hhighlight>1</hhighlight>
<hval1>3.50</hval1>
<hval2>0.00</hval2>
<hsound>0</hsound>
</highlight>
</entity>
</sensorvalue>
<sensorvalue>
<port>MR</port>
</sensorvalue>
<sensorvalue>
<port>MI</port>
<entity>
<eorder>7</eorder>
<ename>Message #</ename>
<eicon>f27a</eicon>
<euom></euom>
<showstatus>0</showstatus>
<mqttcat></mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>7</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>min0</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.00</tvalto>
</translation>
</entity>
</sensorvalue>
</template>
