<template>
<header>
<dtid>0</dtid>
<dtcat>0</dtcat>
<dthw>1.0</dthw>
<minfw>1.4</minfw>
</header>
<sensorvalue>
<port>VB</port>
<entity>
<eorder>1</eorder>
<ename>Battery</ename>
<eicon>f242</eicon>
<euom>V</euom>
<showstatus>1</showstatus>
<mqttcat></mqttcat>
<sendavedelta>0</sendavedelta>
<translation>
<ttype>1</ttype>
<tvisible>1</tvisible>
<tchangeable>1</tchangeable>
<tname>Volts</tname>
<tvalfrom>0.00</tvalfrom>
<tvalto>0.001</tvalto>
</translation>
</entity>
</sensorvalue>
</template>
